In [21]:
!pip install numpy

In [22]:
import numpy as np

In [23]:
vector = [1,2,3,4,5]
print(vector)

[1, 2, 3, 4, 5]


In [24]:
type(vector)

list

In [25]:
#VECTORS array n/b one dimension
vector = np.array([1,2,3,4,5])
print(vector)
type(vector)

[1 2 3 4 5]


numpy.ndarray

In [26]:
#MATRICE when a list takes up multiple dimension
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
matrix_2 = np.array([[1,2,3],[4,5,6]])
print(matrix_2)

[[1 2 3]
 [4 5 6]]


In [28]:
grid_values = np.array([[1,2,3],[4,5,6]])
print(grid_values)

[[1 2 3]
 [4 5 6]]


In [29]:
# to get the shape of the array
grid_values.shape

(2, 3)

In [30]:
#Ones, Zeros (type of array)
ones = np.ones((2,3))
print(ones)



[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
zeros = np.zeros((3,3))
print (zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# Accessing numpy arrays
# np.array[vertical index, horizontal index] - for one element
# np.array [vertical start:vertical end,horizontal start: horizontal end]- for more than one element
grid_values


array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# top left element (slicing)
grid_values[0,0]


1

In [35]:
# first row
grid_values[0,:]

array([1, 2, 3])

In [36]:
#first column
grid_values[:,0]


array([1, 4])

In [38]:
#first two rows and first two columns
grid_values[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [40]:
## Boolean array indexing
#select all values greater than 2 
print(grid_values > 2)
grid_values[grid_values >2]


[[False False  True]
 [ True  True  True]]


array([3, 4, 5, 6])

In [42]:
# select values < 3 and > 5
grid_values[(grid_values < 3) | (grid_values> 5)]

array([1, 2, 6])