In [6]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
vector = [1,2,3,4,5]
print(vector)

[1, 2, 3, 4, 5]


In [9]:
type(vector)

list

In [10]:
#VECTORS array n/b one dimension
vector = np.array([1,2,3,4,5])
print(vector)
type(vector)

[1 2 3 4 5]


numpy.ndarray

In [11]:
#MATRICE when a list takes up multiple dimension
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
matrix_2 = np.array([[1,2,3],[4,5,6]])
print(matrix_2)

[[1 2 3]
 [4 5 6]]


In [13]:
grid_values = np.array([[1,2,3],[4,5,6]])
print(grid_values)

[[1 2 3]
 [4 5 6]]


In [14]:
# to get the shape of the array
grid_values.shape

(2, 3)

In [15]:
#Ones, Zeros (type of array)
ones = np.ones((2,3))
print(ones)



[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
zeros = np.zeros((3,3))
print (zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Accessing numpy arrays
# np.array[vertical index, horizontal index] - for one element
# np.array [vertical start:vertical end,horizontal start: horizontal end]- for more than one element
grid_values


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# top left element (slicing)
grid_values[0,0]


1

In [19]:
# first row
grid_values[0,:]

array([1, 2, 3])

In [20]:
#first column
grid_values[:,0]


array([1, 4])

In [21]:
#first two rows and first two columns
grid_values[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [22]:
## Boolean array indexing
#select all values greater than 2 
print(grid_values > 2)
grid_values[grid_values >2]


[[False False  True]
 [ True  True  True]]


array([3, 4, 5, 6])

In [23]:
# select values < 3 and > 5
grid_values[(grid_values < 3) | (grid_values> 5)]

array([1, 2, 6])

In [26]:
### Modifying numpy Arrays
# adding elements to an array
grid_values

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
grid_values_extra = np.append(grid_values, [[92,88,70]], axis=0)
grid_values_extra

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [92, 88, 70]])

In [27]:
# Example od adding a column
np_column= np.array ([[92],[88],[70]])
grid_values_extra_extra = np.append(grid_values_extra,np_column,axis=1)
grid_values_extra_extra

array([[ 1,  2,  3, 92],
       [ 4,  5,  6, 88],
       [92, 88, 70, 70]])

In [28]:
# Removing elements 
grid_values_del_row = np.delete(grid_values, [1], axis=0)
grid_values_del_row

array([[1, 2, 3]])

In [31]:
#Methods (arrange,reshape,linspace,eye)
#arange
arr = np.arange (0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr_step = np.arange(0,10,2)
arr_step

array([0, 2, 4, 6, 8])

In [35]:
# Reshape
arr.shape

(10,)

In [36]:
arr_reshape = arr.reshape(5,2)
arr_reshape

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
#linspace - allows for even spacing
lin_space =np.linspace(0,20)
lin_space

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [38]:
lin_space =np.linspace(0,20,4)
lin_space

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [40]:
#eye - allows create matrice that you can see the pattern( allows you craft a pattern)
identity_matrix = np.eye(10)
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
#Functions: sum, min,max,argmin,argmax
#sum
grid_values.sum()

21

In [42]:
# sum of each row
grid_values.sum(axis=1)

array([ 6, 15])

In [43]:
#min of each row
grid_values.min(axis=1)

array([1, 4])

In [44]:
#min of each column
grid_values.min(axis=0)

array([1, 2, 3])

In [45]:
# max of each row
grid_values.max(axis=1)

array([3, 6])

In [46]:
# max of each column 
grid_values.max(axis=0)

array([4, 5, 6])

In [47]:
# index of the min of each row
grid_values.argmin(axis=1)

array([0, 0], dtype=int64)

In [48]:
#index of min of each column
grid_values.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [50]:
# index of max of each column 
grid_values.argmax(axis=1)

array([2, 2], dtype=int64)

In [52]:
# index of max of each column 
grid_values.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [51]:
grid_values

array([[1, 2, 3],
       [4, 5, 6]])

### Random: rand,randn, randint

In [56]:
# rand : 0 & 1
rand_arr = np.random.rand(3,4)
rand_arr

array([[0.32939033, 0.69727779, 0.90615381, 0.14299573],
       [0.25497443, 0.29382857, 0.32974215, 0.59307065],
       [0.89428475, 0.21953107, 0.24425716, 0.67628283]])

In [57]:
# randn : from standard normal distribution
randn_arr = np.random.randn(3,3)
randn_arr

array([[-0.46235842, -0.3977877 ,  1.40389953],
       [-0.14617092, -0.82491145,  0.01589788],
       [-0.77288153, -0.85270843, -1.77736737]])

In [66]:
# randint: 1 - 100
randint_arr = np.random.randint(1, 10, size=(3,5))
randint_arr


array([[2, 1, 7, 6, 1],
       [4, 8, 5, 4, 3],
       [8, 9, 4, 5, 6]])